### ISSUE TITLE
Assets not loaded on dedicated server

### ISSUE THREAD

**Issue by moadib** [fmod/fmod-for-unreal#29]
Simple case: some blueprint has serverside logic and reference to FMODEvent. At certain circumstances it want to send Client RPC with name of event, so client can use FindEventByName and play it. It can be don by passing FMODUtils::LookupNameFromGuid(Event->AssetGuid);

On dedicated server all FMODEvent references contains nullptr, log contains messages like this:
`LogStreaming: Error: Couldn't find file for package /Game/FMOD/Events/object/tree requested by async loading code. NameToLoad: /Game/FMOD/Events/object/tree`.
They are created earlier, since log contains `Constructing asset: /Game/FMOD/Events/object/tree` but not finded by loader.

**Comment by HanzaRu** [comment]
This issue appeared also on our dedicated servers, and this fix resolved the problem.
